alias sudo='sudo -v; sudo '
alias sduo='sudo -v; sudo '
alias df='df -hT'
alias apt='sudo apt'
alias upd='pkcon update'
alias mv='mv -i'
alias windinfo='xwininfo -stats -wm'
#alias get='aria2c dir=${HOME}/Download file-allocation=falloc on-download-complete=exit log-level=warn max-connection-per-server=8 min-split-size=5M'
#alias play='gst123' 
#alias mp='mocp'
